# Generated by Django 4.2.1 on 2023-05-20 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('systolic', models.IntegerField(blank=True, null=True)),
                ('diastolic', models.IntegerField(blank=True, null=True)),
                ('blood_glucose', models.IntegerField(blank=True, null=True)),
                ('resting_metabolic_rate', models.IntegerField(blank=True, null=True)),
                ('cholesterol', models.IntegerField(blank=True, null=True)),
                ('low_density_lipoprotein', models.IntegerField(blank=True, null=True)),
                ('high_density_lipoprotein', models.IntegerField(blank=True, null=True)),
                ('triglycerides', models.IntegerField(blank=True, null=True)),
                ('vo2', models.IntegerField(blank=True, null=True)),
                ('sleep_score', models.IntegerField(blank=True, null=True)),
                ('stress_score', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
